osx_image: xcode9.2
language: objective-c

script:
  - cmake .
  - make

notifications:
  slack:
    - secure: "HydHv8l0O0zlRj2C7x/e270R0+cP09rwxMbDKfJTCvrc6v2PSXsrzLerHrSfBBir3zYS+qMM0EPs6wtDbRwFpmPePPM47xfT5mSEarIoU1gHRwRZd+C2UVQepsXkgdePXO8Qh2sAp7Qk37pQSl7wU+ZieToTbf9j1ZaIMKTajBmKsJjk2UMQP/3iAmn0IAl8LjFuT2dbLU07Ouccc4vcpKSaVKih3jCkzvhfujJsKSTlcbmXzyTMVzLQPRbZQGAcCqv5B6D+YcG3ADzbZ4cN6UokmpdZ2tXWTOG63mPMiaZtMIhkdeh8YDmKOoTab5wfoNhSEu983JdkaW/wtlr1EAQCe4zjh5toxf4oPtme9OfpJ7MJSV7+MX+s4yMgoOiCoho93hnCdoU3bm9AeJ68YAGQBvK21kO6PhGv0OZVZcXowyFybM0PyLzRJQZ0l1Io/bGgWmKYp193sQBral+J9aYdJNaH8bWbJ4OMmXRj/7z12tW6ReZXWp7EHp7Ju5byr+6/NjKvYgWIXUfNHNAoCQE3a5O5eSm11cf8WR4gFekiQJOcAdX0gyxemGGIzqT3Pb7IRsL908T5HgdmqYJxG2QIFqL7F8x1QniyS0BEBNcS64iATpDV71K06GLkxQnDQuoXyhNZkoiFIXQwQ1YglXs9FUIgE72iei2DXgeDzdk="
