osx_image: xcode9.2
language: objective-c

script:
  - cmake .
  - make

notifications:
  slack:
    - secure: "inm2KjS5CodN5V7heZFxB9ZV2OE/hbyacIr/saAJ94HJR3xN9c9nN0XKFAmh3KWhjOx72epOcSvTNKarAuvVjtFQ7miPbVZhhs/AipAEvfo47bSJsNDaWyLbeeOFJqBJ0EUJ9WD2YLDk6RLt+75ZRC2uM4adAOY02O5BKz03GLDLkJeryOr1Bt+jEHVDX29VwLCoIEc6WVrQlSZj1gAMqq32iyAnCQMrMQAdOc1FTYjsTJ0W+Agynofwxu1KpQSZpeWG69rkwik7eaMNW8zzsbg5ILueNB61c6Cpi/8h0J6TmV5/bylnvpxXiRsHikldLIKzBRw4AdhNMjtVD4InWvwFbkD2jzhN0QPaDhlOjzYMaakH1rVnanmsOJRGiF7I++Xxm0iM2anbRsr1jIxF2OMfJGWPI1CQjQ15+p+21YQF7SKDZaPP8A/lpNYmORYBP6paqM11mDp4YS2Xt8VnVsQYLG9FGCSEvc/7WQz/YOQ4rGgcNHYwPhegMI24PHVfhOBCtmArqb1ymR+xQENh0bhdKImIwxmNIlBaQwEbs3I3gTtNeUTCm+YF+a/pQvhNnr6sxqXafv4ogh4nNTp9iexJgiyv8uA2GdhiXWp/+P3fha2WwtNLlC1t8/c2pnHTDGqGvCoOS9nwPUCD9LMbJZgbiXIUW6V5sUHiaMrMzto="

