version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: System information
          command: |
            gcc --version
            apt-get update
            apt-get install cmake g++ python libfontconfig1-dev \
              libx11-dev libxcomposite-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev -y
      - run:
          name: Build
          command: |
            cmake .
            make
